config/routes.rb
Rails.application.routes.draw do
  resources :coffeees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffeee.rb
class Coffeee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coffeees_controller.rb
class CoffeeesController < ApplicationController
  before_action :set_coffeee, only: [:show, :edit, :update, :destroy]

  # GET /coffeees
  # GET /coffeees.json
  def index
    @coffeees = Coffeee.all
  end

  # GET /coffeees/1
  # GET /coffeees/1.json
  def show
  end

  # GET /coffeees/new
  def new
    @coffeee = Coffeee.new
  end

  # GET /coffeees/1/edit
  def edit
  end

  # POST /coffeees
  # POST /coffeees.json
  def create
    @coffeee = Coffeee.new(coffeee_params)

    respond_to do |format|
      if @coffeee.save
        format.html { redirect_to @coffeee, notice: 'Coffeee was successfully created.' }
        format.json { render :show, status: :created, location: @coffeee }
      else
        format.html { render :new }
        format.json { render json: @coffeee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffeees/1
  # PATCH/PUT /coffeees/1.json
  def update
    respond_to do |format|
      if @coffeee.update(coffeee_params)
        format.html { redirect_to @coffeee, notice: 'Coffeee was successfully updated.' }
        format.json { render :show, status: :ok, location: @coffeee }
      else
        format.html { render :edit }
        format.json { render json: @coffeee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffeees/1
  # DELETE /coffeees/1.json
  def destroy
    @coffeee.destroy
    respond_to do |format|
      format.html { redirect_to coffeees_url, notice: 'Coffeee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffeee
      @coffeee = Coffeee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffeee_params
      params.require(:coffeee).permit(:name, :type, :desctrption, :home, :img, :something)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffeees_helper.rb
module CoffeeesHelper
end

app/views/coffeees/_form.html.erb
<%= form_with(model: coffeee, local: true) do |form| %>
  <% if coffeee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffeee.errors.count, "error") %> prohibited this coffeee from being saved:</h2>

      <ul>
      <% coffeee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :desctrption %>
    <%= form.text_field :desctrption %>
  </div>

  <div class="field">
    <%= form.label :home %>
    <%= form.text_field :home %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="field">
    <%= form.label :something %>
    <%= form.text_field :something %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coffeees/edit.html.erb
<h1>Editing Coffeee</h1>

<%= render 'form', coffeee: @coffeee %>

<%= link_to 'Show', @coffeee %> |
<%= link_to 'Back', coffeees_path %>

app/views/coffeees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffeees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Desctrption</th>
      <th>Home</th>
      <th>Img</th>
      <th>Something</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffeees.each do |coffeee| %>
      <tr>
        <td><%= coffeee.name %></td>
        <td><%= coffeee.type %></td>
        <td><%= coffeee.desctrption %></td>
        <td><%= coffeee.home %></td>
        <td><%= coffeee.img %></td>
        <td><%= coffeee.something %></td>
        <td><%= link_to 'Show', coffeee %></td>
        <td><%= link_to 'Edit', edit_coffeee_path(coffeee) %></td>
        <td><%= link_to 'Destroy', coffeee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffeee', new_coffeee_path %>

app/views/coffeees/new.html.erb
<h1>New Coffeee</h1>

<%= render 'form', coffeee: @coffeee %>

<%= link_to 'Back', coffeees_path %>

app/views/coffeees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coffeee.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @coffeee.type %>
</p>

<p>
  <strong>Desctrption:</strong>
  <%= @coffeee.desctrption %>
</p>

<p>
  <strong>Home:</strong>
  <%= @coffeee.home %>
</p>

<p>
  <strong>Img:</strong>
  <%= @coffeee.img %>
</p>

<p>
  <strong>Something:</strong>
  <%= @coffeee.something %>
</p>

<%= link_to 'Edit', edit_coffeee_path(@coffeee) %> |
<%= link_to 'Back', coffeees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharkapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>